In [1]:
import numpy as np

###  Input Features

In [2]:
input_feat= np.array([[0,0],[0,1],[1,0],[1,1]])
print(input_feat)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


### Output Features

In [3]:
output_feat = np.array([[0,0,0,1]])
print(output_feat)
print(output_feat.shape)
output_feat = output_feat.reshape(4,1)

print(output_feat)

[[0 0 0 1]]
(1, 4)
[[0]
 [0]
 [0]
 [1]]


### Assigning weights 

In [4]:
weights = np.array([[0.2],[0.3]])
print("Weights Shape",weights.shape)    
print(weights)

Weights Shape (2, 1)
[[0.2]
 [0.3]]


#### Addition of Learning Rate and Bias

In [5]:
lr = 0.05   
bias = 0.3  

#### Sigmoid Function

In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))     # 1/1+e^-x  rnage of values from 0~1

#### Derivative of Sigmoid function

In [7]:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

#### Training and updation of weigths

In [9]:


for i in range(50000):
    inputs = input_feat
   # print(inputs.shape)
    in_o = np.dot(inputs,weights) + bias
    out_o = sigmoid(in_o)
    error = (out_o - output_feat)     
    x = error.sum()
  #  print(x)
    derror_douto = error
    dout_din = sigmoid_der(out_o)
    deriv = derror_douto * dout_din
    inputs = input_feat.T
    #print(inputs.shape)
    deriv_final = np.dot(inputs,deriv)
   # print(deriv_final.shape)
    #updating the weights
    weights -= lr * deriv_final
    #print(weights.shape)
    for i in deriv:
        bias -= lr * i


#### Checking Value of weights and Bias

In [10]:
print(weights)
print(bias)

[[9.04827674]
 [9.04827674]]
[-13.86063047]


#### Predicting Value

In [12]:
inp = np.array([1,0])
result_1 = np.dot(inp,weights) + bias
result_2 = sigmoid(result_1)
print(result_2)

[0.00806316]


In [13]:
inp = np.array([1,1])
result_1 = np.dot(inp,weights) + bias
result_2 = sigmoid(result_1)
print(result_2)

[0.98573984]


In [14]:
inp = np.array([1,0])
result_1 = np.dot(inp,weights) + bias
result_2 = sigmoid(result_1)
print(result_2)

[0.00806316]


In [15]:
inp = np.array([0,0])
result_1 = np.dot(inp,weights) + bias
result_2 = sigmoid(result_1)
print(result_2)

[9.55881943e-07]
